Blog_App/urls.py
from django.urls import path
from Blog_App import views

app_name = 'Blog_App'
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('create-post/', views.CreatePost.as_view(), name='create_post'),
    path('Post-details/<slug:slug>', views.post_details, name='post_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('edit-post/<pk>/', views.EditPost.as_view(), name='edit_post'),
    path('delete-post/<pk>/', views.DeletePost.as_view(), name= 'delete_post'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_App.urls')),
    path('blog/', include('Blog_App.urls')),
    path('', views.index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login_App/urls.py
from django.urls import path
from Login_App import views



app_name = 'Login_App'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('password/', views.password_change, name='password_change'),
    path('add-profilepic/', views.add_profile_Image, name='add_profile_Image'),
    path('change-profilepic/', views.change_profile_image, name='change_profile_image'),
]

Blog_App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=250, verbose_name="Tilte")
    slug = models.SlugField(max_length=250, unique=True)
    blog_content = models.TextField(verbose_name="Content")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date']

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="blog_like")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_like")

    # def __str__(self):
    #     return self.user + "likes" + self.blog

Blog_App/forms.py
from django import forms
from Blog_App.models import Blog, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

Blog_App/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.views.generic import CreateView, UpdateView, DetailView, View, TemplateView, DeleteView, ListView
from Blog_App.models import Blog, Comment, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from Blog_App.forms import CommentForm


# Create your views here.


class CreatePost(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'Blog_App/create_post.html'
    fields = ('blog_title', 'blog_content', 'blog_image')


    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

class PostList(ListView):
    context_object_name= 'posts'
    model = Blog
    template_name = 'Blog_App/Post_list.html'

@login_required
def post_details(request, slug):
    post = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=post, user= request.user)
    if already_liked:
        liked = True
    else:
        liked = False

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = post
            comment.save()
            return HttpResponseRedirect(reverse('Blog_App:post_details', kwargs={'slug':slug}))

    return render(request, 'Blog_App/post_details.html', context={'post':post, 'comment_form':comment_form, 'liked':liked,})


@login_required
def liked(request, pk):
    post = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=post, user=user)
    if not already_liked:
        liked_post = Likes(blog=post, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('Blog_App:post_details', kwargs={'slug':post.slug}))

@login_required
def unliked(request, pk):
    post = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=post, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('Blog_App:post_details', kwargs={'slug':post.slug}))

class EditPost(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'Blog_App/edit_post.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('Blog_App:post_details', kwargs={'slug':self.object.slug})

class DeletePost(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'Blog_App/delete_post.html'
    success_url = reverse_lazy("Login_App:profile")

templates/Blog_App/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Create Post
{% endblock %}

{% block body %}
<h1>Create Your Post</h1>
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy}}
  {% csrf_token %}
  <br>
  <button class="btn btn-info" type="submit" name="button">Plublish</button>
</form>
{% endblock %}

templates/Blog_App/delete_post.html
<h5>Delete Post</h5>

<form method="POST">
{% csrf_token %}
<input type="submit" name="submit" value="Delete" class="btn btn-danger">

<a href="{% url 'Login_App:profile' %}">Cancel</a>
</form>

templates/Blog_App/edit_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
Create Post
{% endblock %}

{% block body %}
{% if blog.author == user %}
<h1>Edit Your Post</h1>
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy}}
  {% csrf_token %}
  <br>
  <button class="btn btn-info" type="submit" name="button">Plublish</button>
</form>
{% else %}
<h5>Your are not permission for edit post!</h5>
{% endif %}
{% endblock %}

templates/Blog_App/post_details.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block title_block %}
{{post.blog_title}}
{% endblock %}

{% block body %}

<h2>{{post.blog_title}}</h2>
<h4>Posted by : {{post.author}}</h4> <i><h6>Published : {{post.publish_date}} Last Update : {{post.update_date}}</h6></i>
<h5>{{post.blog_like.count}} Like | {{post.blog_comment.count}} Comment</h5>
<br>
<div class="text-center">


<img src="/media/{{post.blog_image}}" alt="" width="300px">
</div>
<br>
<p>{{post.blog_content|linebreaks}}</p>
<hr>
{% if not liked %}
<a href="{% url 'Blog_App:liked_post' pk=post.pk %}">
<i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"> </i>
</a>
{% else %}
<a href="{% url 'Blog_App:unliked_post' pk=post.pk %}">
<i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"> </i>
</a>
{% endif %}
<br>
<div class="">
  <form class="" method="POST">
    {{ comment_form|crispy }}
    {% csrf_token %}
    <br>
    <button type="submit" class="btn btn-info btn-sm">Submit</button>
  </form>
</div>
<div>
  <h3>Latest Comment</h3>
  {% for comment in post.blog_comment.all %}
    <h6>{{comment.user}} | {{comment.comment_date}}</h6>
    <p>{{comment.comment}}</p>
    <hr>
  {% endfor %}

</div>

{% endblock %}

templates/Blog_App/post_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %}
Home
{% endblock %}

{% block body %}
{% for post in posts %}
<br>
<div class="card" style="width: 80rem;" href="{% url 'Blog_App:post_details' slug=post.slug %}">
<h2>{{post.blog_title}}</h2>

<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{post.blog_image}}" alt="{{post.blog_title}}" title="{{post.blog_title}}" width="420px" height="260px">

  </div>
  <div class="col-sm-8">
    <p>{{post.blog_content|range_filter|linebreaks}} <a href="{% url 'Blog_App:post_details' slug=post.slug %}">see more</a></p>
    <h6>Posted By :<a href="{% url 'Login_App:profile' %}">{{post.author}}</a></h6>
    <h6>Plublish : {{post.publish_date}}  [ {{post.blog_like.count}} Like | {{post.blog_comment.count}} Comment]</h6>


    {% if post.author == user %}
    <a href="{% url 'Blog_App:edit_post' pk=post.pk %}">Edit Post</a> |
    <a href="{% url 'Blog_App:delete_post' pk=post.pk %}">Delete Post</a>
    {% endif %}
  </div>

</div>
</div>
<br>
{% endfor %}
{% endblock %}