Blog_App/urls.py
from django.urls import path
from Blog_App import views

app_name = 'Blog_App'
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('create-post/', views.CreatePost.as_view(), name='create_post'),
    path('Post-details/<slug:slug>', views.post_details, name='post_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('edit-post/<pk>/', views.EditPost.as_view(), name='edit_post'),
    path('delete-post/<pk>/', views.DeletePost.as_view(), name= 'delete_post'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_App.urls')),
    path('blog/', include('Blog_App.urls')),
    path('', views.index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login_App/urls.py
from django.urls import path
from Login_App import views



app_name = 'Login_App'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('password/', views.password_change, name='password_change'),
    path('add-profilepic/', views.add_profile_Image, name='add_profile_Image'),
    path('change-profilepic/', views.change_profile_image, name='change_profile_image'),
]

Login_App/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

Login_App/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from Login_App.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserProfileUpdate(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')


class ProfileImage(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic',]

Login_App/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Login_App.forms import SignUpForm, UserProfileUpdate, ProfileImage


def signup(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    context = {'form':form, 'registered':registered}
    return render(request, 'Login_App/signup.html', context = context)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('Blog_App:post_list'))

    return render(request, 'Login_App/login.html', context={'form':form})

@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('Blog_App:post_list'))


@login_required

def profile(request):
    return render(request, 'Login_App/profile.html')

@login_required
def profile_update(request):
    current_user = request.user
    form = UserProfileUpdate(instance=current_user)
    if request.method == 'POST':
        form = UserProfileUpdate(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileUpdate(instance=current_user)
    return render(request, 'Login_App/profile_update.html', context={'form':form})

@login_required
def password_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'Login_App/password_change.html', context={'form':form, 'changed':changed})



@login_required
def add_profile_Image(request):
    form = ProfileImage()
    if request.method == 'POST':
        form = ProfileImage(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('Login_App:profile'))
    return render(request, 'Login_App/add_profile_Image.html', context={'form':form})


@login_required
def change_profile_image(request):
    form = ProfileImage(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfileImage(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('Login_App:profile'))
    return render(request, 'Login_App/add_profile_Image.html', context={'form':form})

templates/Login_App/add_profile_Image.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}

{% block body %}
<h2>Add Profile Picture</h2>
<img class="rounded-circle" width="100px" src="/media/{{user.user_profile.profile_pic}}" alt="">
<form class="" method="POST" enctype="multipart/form-data">
  {{form|crispy}}
  {% csrf_token %}
  <button class="btn btn-success" type="Submit" name="submit">Update</button>
</form>
{% endblock %}

templates/Login_App/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}

{% block body %}

<h3>Create New Account</h3>
<form class="" method="POST">
  {{form|crispy}}
  {% csrf_token %}
  <button class="btn btn-success" type="Submit" name="submit">Login</button>
</form>

<br>
<p>Don't have Account! Please <a href="{% url 'Login_App:signup' %}">Signup</a></p>

{% endblock %}

templates/Login_App/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Password {% endblock %}

{% block body %}
{% if changed %}
<div class="alert alert-success">
  Password Changed Successfully!👌

</div>
{% endif %}

<form class="" method="POST">
{{ form|crispy }}
{% csrf_token %}

<button type="submit" class="btn btn-success">Change</button>
</form>
{% endblock %}

templates/Login_App/profile.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}

{% block body %}
<h2>My Profile</h2>

{% if user.user_profile %}
<img class="rounded-circle" width="100px" src="/media/{{user.user_profile.profile_pic}}" alt="">
<br>
<a class="btn btn-info btn-sm" href="{% url 'Login_App:change_profile_image' %}">Change Image</a>
{% else %}
<img class="rounded-circle" width="100px" src="/media/profile_pics/profile.jpg" alt="">
<br>
<br>
<a class="btn btn-info btn-sm" href="{% url 'Login_App:add_profile_Image' %}">Add Image</a>
{% endif %}
<p>Username : {{user.username}}</p>
<p>Name : {{user.first_name}} {{user.last_name}}</p>
<p>Email : {{user.email}}</p>
<h6>Total Like : {{user.user_like.count}} | Total Comment : {{user.user_comment.count}}</h6>
<br>
<a class="btn btn-warning" href="{% url 'Login_App:profile_update' %}">Edit Profile</a>
<hr>
<h6>Total Published Post : {{user.post_author.count}}</h6>
{% for post in user.post_author.all %}
<h1>{{post.blog_title}}</h1>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{post.blog_image}}" alt="{{post.blog_title}}" title="{{post.blog_title}}" width="200px">

  </div>
  <div class="col-sm-8">
    <p>{{post.blog_content|range_filter|linebreaks}} <a href="{% url 'Blog_App:post_details' slug=post.slug %}">see more</a></p>
    <h6>Posted By :<a href="{% url 'Login_App:profile' %}">{{post.author}}</a></h6>
    <h6>Plublish : {{post.publish_date}}   {{post.blog_like.count}} Like | {{post.blog_comment.count}} Comment</h6>
  </div>
</div>
<a href="{% url 'Blog_App:edit_post' pk=post.pk %}">Edit Post</a>
<a href="{% url 'Blog_App:delete_post' pk=post.pk %}">Delete Post</a>
<hr>
{% endfor %}
{% endblock %}

templates/Login_App/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile Update {% endblock %}

{% block body %}
<form class="" method="POST">
{{ form|crispy }}
{% csrf_token %}
<p>Forgot password! <a href="{% url 'Login_App:password_change' %}">Click Here</a></p>
<button type="submit" class="btn btn-success">Update</button>
</form>
{% endblock %}

templates/Login_App/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %}

{% block body %}
{% if registered %}
<div class="alert alert-success">
  Acoount Create Successfully <a href="{% url 'Login_App:login' %}">Login here</a>
</div>
{% else %}
<h3>Create New Account</h3>
<form class="" method="POST">
  {{form|crispy}}
  {% csrf_token %}
  <button class="btn btn-success" type="Submit" name="submit">Create</button>
</form>

<br>
<p>Already have a account? <a href="{% url 'Login_App:login' %}">Login</a></p>
{% endif %}
{% endblock %}