Blog_App/urls.py
from django.urls import path
from Blog_App import views

app_name = 'Blog_App'
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('create-post/', views.CreatePost.as_view(), name='create_post'),
    path('Post-details/<slug:slug>', views.post_details, name='post_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('edit-post/<pk>/', views.EditPost.as_view(), name='edit_post'),
    path('delete-post/<pk>/', views.DeletePost.as_view(), name= 'delete_post'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_App.urls')),
    path('blog/', include('Blog_App.urls')),
    path('', views.index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Login_App/urls.py
from django.urls import path
from Login_App import views



app_name = 'Login_App'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('password/', views.password_change, name='password_change'),
    path('add-profilepic/', views.add_profile_Image, name='add_profile_Image'),
    path('change-profilepic/', views.change_profile_image, name='change_profile_image'),
]

Blog_Project/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect

def index(request):
    return HttpResponseRedirect(reverse('Blog_App:post_list'))

Blog_Project/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>{% block title_block %} Blog {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/blog/">Home</a>
    <a class="navbar-brand" href="{% url 'Blog_App:create_post' %}">Create Post</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">


    </div>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Login_App:logout' %}">Logout</a>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Login_App:profile' %}"><img class="rounded-circle" width="30px" src="/media/{{user.user_profile.profile_pic}}" alt="">{{user.first_name}} {{user.last_name}}</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Login_App:signup' %}">Signup</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Login_App:login' %}">Login</a>
      </li>

      {% endif %}
    </ul>
  </div>

</nav>

<div class="container">



{% block body %}

{% endblock %}

</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>